### ISSUE TITLE
Compiling issue on Windows 7

### ISSUE THREAD

**Issue by lbabaly** [NordicSemiconductor/pc-ble-driver-js#6]
Hello, 

I'm trying to install on Windows 7 but I get the following error:

CMake Error at CMakeLists.txt:4 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:4 (project):
  No CMAKE_CXX_COMPILER could be found.

I have Visual Studio 2015 installed on my system.
Looking at the build directory and checking the CMakeError.log I found this:
LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\Users\user\Documents\GitHub\pc-ble-driver-js\build\CMakeFiles\3.5.0-rc2\CompilerIdC\CompilerIdC.vcxproj]

Any idea how to resolve this issue?

Thanks,
Laszlo

**Comment by kenr** [comment]
We've had issues compiling with Visual Studio 2015, I recommend that you install Visual Studio 2013.

We will release precompiled versions of the driver at a later time so that you do not have to go through all the steps to get a driver up and running.

Below are instructions on how to compile the driver your self. Please let me know if it works or not.

## Windows install instructions (x86)

These instructions are for NodeJS versions compiled for X86.

## Install CMake
Install version 2.8 or newer from https://cmake.org/download/

## Install and compile Boost libraries

Download the Boost libraries from (.zip):
https://sourceforge.net/projects/boost/files/boost/1.56.0/

1. Create folder c:\\boost
2. Unzip the libraries into folder c:\\boost, you shall end up with a path like c:\\boost\\boost_1_56_0
3. Start "VS2013 x86 Native Tools Command Prompt". The command prompt is found in the Start menu->Visual Studio 2013->Visual Studio Tools).
4. Run the following commands:

```
cd c:\\boost\\boost_1_56_0
bootstrap
b2 toolset=msvc-12.0 address-model=32 link=static --with-thread --with-system --with-regex --with-date_time --with-chrono

```

## Compile pc-ble-driver-js

Still in the "VS2013 x86 Native Tools Command Prompt", run the following commands:
```

npm config set cmake_CMAKE_GENERATOR:INTERNAL="Visual Studio 12 2013" 
set npm_config_arch=ia32
set npm_config_target=<installed NodeJS version>
npm i

```

Since Windows do not have a rpath like mechanism you have to copy the pc-ble-driver.dll to the directory of your JavaScript file.

If this does not work, please feel to reopen the issue and revert back to me and I'll look into it.
