### ISSUE TITLE
pc-ble-driver subrepo not in release artifacts

### ISSUE THREAD

**Issue by IvanSanchez** [NordicSemiconductor/pc-ble-driver-js#67]
The `/pc-ble-driver` subrepo is not in the release artifacts (the .zip/.tar.gz files at https://github.com/NordicSemiconductor/pc-ble-driver-js/releases , e.g. https://github.com/NordicSemiconductor/pc-ble-driver-js/archive/v2.0.0.zip ).

This means that trying to `npm install pc-ble-driver`, or trying to run `npm install` from a freshly checked-out `pc-nrfconnect-core` will fail (npm/yarn will not check out the subrepo, and the directory will be empty).

The approach is to perform a release by branching `master`, committing the needed files (turning `pc-ble-driver` from a subrepo into plain committed files), and tagging that as the release.

**Comment by IvanSanchez** [comment]
This is alleviated by https://github.com/NordicSemiconductor/pc-ble-driver-js/commit/b8feb9335a38ddb373f2b546b8c696060f86f598 by providing a clearer message when `npm install`ing a freshly checked-out repo, but `npm install pc-ble-driver` is still an issue.

**Comment by mrodem** [comment]
The submodule is fetched when when installing with npm. However, yarn does not fetch submodules, ref. https://github.com/yarnpkg/yarn/issues/1488.

Because of this it is unfortunately not possible to use yarn when depending on a Git repository that uses submodules, like pc-ble-driver-js. Yarn users need to either apply one of the workarounds proposed in the given issue or use npm.
